import { MATCHUPS } from "@/data/playoffs";
import { MatchupCard } from "@/components/MatchupCard";
import { RebuttalArena } from "@/components/RebuttalArena";

const Index = () => {
  const east = MATCHUPS.filter((m) => m.conf === "East");
  const west = MATCHUPS.filter((m) => m.conf === "West");

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <header className="relative overflow-hidden border-b border-border/60">
        <div className="absolute inset-0 pointer-events-none" style={{ backgroundImage: "var(--gradient-hero)" }} />
        <div className="container relative py-14 md:py-20">
          <div className="flex items-center gap-2 mb-4">
            <span className="h-2 w-2 rounded-full bg-primary animate-pulse-glow" />
            <span className="text-[11px] uppercase tracking-widest text-muted-foreground">
              Live · 1st Round · April 2026
            </span>
          </div>
          <h1 className="font-display text-5xl md:text-7xl lg:text-8xl leading-[0.9]">
            Hardwood <span className="text-primary">2026</span>
          </h1>
          <p className="mt-4 text-base md:text-lg text-muted-foreground max-w-2xl">
            AI-powered series predictions, confidence scores, and rebuttals to your hottest takes.
            The 2026 NBA Playoffs, decoded matchup by matchup.
          </p>

          <div className="mt-8 flex items-center gap-6 text-xs text-muted-foreground">
            <Stat label="Active Series" value="8" />
            <Divider />
            <Stat label="Conferences" value="2" />
            <Divider />
            <Stat label="Round" value="1st" />
          </div>
        </div>
      </header>

      <main className="container py-12 space-y-16">
        <ConferenceSection title="Eastern Conference" accent="east" matchups={east} />
        <ConferenceSection title="Western Conference" accent="west" matchups={west} />

        <section className="pt-4">
          <RebuttalArena />
        </section>
      </main>

      <footer className="border-t border-border/60 mt-16">
        <div className="container py-8 text-center text-xs text-muted-foreground">
          Predictions generated by Lovable AI · Not affiliated with the NBA · Records and matchups for entertainment.
        </div>
      </footer>
    </div>
  );
};

const ConferenceSection = ({
  title, accent, matchups,
}: { title: string; accent: "east" | "west"; matchups: typeof MATCHUPS }) => (
  <section>
    <div className="flex items-center gap-4 mb-6">
      <div
        className="h-8 w-1.5 rounded-full"
        style={{ background: `hsl(var(--${accent}))`, boxShadow: `0 0 24px hsl(var(--${accent}) / 0.6)` }}
      />
      <h2 className="font-display text-3xl md:text-4xl">{title}</h2>
      <div className="flex-1 scoreline" />
      <span className="text-[10px] uppercase tracking-widest text-muted-foreground">First Round</span>
    </div>
    <div className="grid gap-5 md:grid-cols-2">
      {matchups.map((m) => <MatchupCard key={m.id} matchup={m} />)}
    </div>
  </section>
);

const Stat = ({ label, value }: { label: string; value: string }) => (
  <div>
    <div className="font-display text-2xl text-foreground leading-none">{value}</div>
    <div className="text-[10px] uppercase tracking-widest mt-1">{label}</div>
  </div>
);

const Divider = () => <div className="h-8 w-px bg-border" />;

export default Index;
